const LOGIN = 'LOGIN'
const LOGINOUT = 'LOGINOUT'
const LOADGOODS = 'LOADGOODS'
const ADDNUM = 'ADDNUM'
const REDNUM = 'REDNUM'
const DELETEGOOD = 'DELETEGOOD'
export {LOGIN, LOGINOUT, LOADGOODS, ADDNUM, REDNUM, DELETEGOOD}