const GET_SHOWING_LIST = 'GET_SHOWING_LIST'
const GET_WILLSHOW_LIST = 'GET_WILLSHOW_LIST'
const GET_MORE_LIST = 'GET_MORE_LIST'
const GET_MORE_MOVIES = 'GET_MORE_MOVIES'
const GET_DETAIL = 'GET_DETAIL'
const BUY_TICKET = 'BUY_TICKET'
export {GET_SHOWING_LIST, GET_WILLSHOW_LIST, GET_MORE_MOVIES, GET_MORE_LIST, GET_DETAIL, BUY_TICKET}